AT 17.04 | Page-header > Open builds from dropdown menu
RedRoverSchool/JenkinsQA_06 pull request #1618
Opened 2023-05-10 21:34 UTC by Yuliya48

https://trello.com/c/0bksJgld/348-at-0204-pipeline-configure-set-discarding-of-old-builds-with-0-builds-to-keep

2023-05-11 03:12 UTC, MaxMishch requested changes

2023-05-11 03:12 UTC, MaxMishch commented on src/test/java/school/redrover/PageHeaderAdminDropdownMenuTest.java
> +                (By.xpath("//span[.='Builds']")));
It seems this xpath locator is not unique, let's try (By.xpath("(//span[.='Builds'])[1]"))

2023-05-11 14:18 UTC, Yuliya48 commented on src/test/java/school/redrover/PageHeaderAdminDropdownMenuTest.java
> +                (By.xpath("//span[.='Builds']")));
I added changes

2023-05-12 13:03 UTC, KathyGU approved these changes

2023-05-12 13:11 UTC, MaxMishch approved these changes

2023-05-12 13:12 UTC, merged