Add method pipeline creation & and a test for deletion
RedRoverSchool/JenkinsQA_06 pull request #1687
Opened 2023-05-12 00:32 UTC by Kk-788

2023-05-14 20:23 UTC, Kk-788 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 02.05 | Pipeline > Delete Pipeline > DeletePipelineTest_2](https://trello.com/c/pYh75jXv/620-at-0205-pipeline-delete-pipeline-deletepipelinetest2)

2023-05-14 20:23 UTC, Kk-788 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 02.05 | Pipeline > Delete Pipeline > DeletePipelineTest_2](https://trello.com/c/pYh75jXv/620-at-0205-pipeline-delete-pipeline-deletepipelinetest2)

2023-05-14 21:54 UTC, ArinaJur approved these changes

2023-05-14 23:46 UTC, Maria7725 requested changes

2023-05-14 23:46 UTC, Maria7725 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +//    {"method":"xpath","selector":"//button[@formnovalidate='formNoValidate']"}
What is the purpose to add those comments with the @Ignor annotation? Why those lines were not deleted?

2023-05-14 23:46 UTC, Maria7725 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +//    {"method":"xpath","selector":"//div[@id='main-panel']/h1"}
Same question as about lines 52-54.

2023-05-15 00:07 UTC, Kk-788 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +//    {"method":"xpath","selector":"//button[@formnovalidate='formNoValidate']"}
I left those comments there for the author of the failed test to know why the test was ignored, and what needs to be changed. This is especially important considering that the errors did not show up 100% of the time. After the issue is resolved, the comments are obviously intended to be deleted along with the @Ignore annotation.

2023-05-15 01:52 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +//    {"method":"xpath","selector":"//button[@formnovalidate='formNoValidate']"}
Nothing harmful for the system in those comments. They are not affecting the CI

2023-05-15 02:33 UTC, Kk-788 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +//    {"method":"xpath","selector":"//button[@formnovalidate='formNoValidate']"}
Exactly. They are supposed to be temporary anyway.

2023-05-16 06:28 UTC, merged