AT 00.00 CreateNewItem
RedRoverSchool/JenkinsQA_06 pull request #1771
Opened 2023-05-13 13:02 UTC by davidmav19

2023-05-13 13:10 UTC, NataliaKubiak approved these changes

2023-05-13 13:46 UTC, ArinaJur requested changes
Please add assert to your test. What are you verifying?

2023-05-13 14:11 UTC, ArtyomDulya commented
and add us to which you wrote AT to the AT card

2023-05-13 14:12 UTC, ArtyomDulya commented
and add US to which you wrote AT to the AT card

2023-05-13 14:14 UTC, ArtyomDulya commented
Please add US to which you wrote AT to the AT card

2023-05-13 14:42 UTC, VictoriaLema approved these changes

2023-05-13 14:42 UTC, VictoriaLema commented on src/test/java/school/redrover/NewItemJenkinsTest.java
> +public class NewItemJenkinsTest extends BaseTest {
нужна пустая строка перед именем класса, и только  одна между именем теста и именем класса

2023-05-13 14:42 UTC, VictoriaLema commented on src/test/java/school/redrover/NewItemJenkinsTest.java
> +        public void createNewJob()
название должно быть testCreateNewJob (т.е. начинаться с test), а также лучше написать, какй именно job (pipeline, folder). скобка должна быть не на 12 строке, а на 11

2023-05-13 14:42 UTC, VictoriaLema commented on src/test/java/school/redrover/NewItemJenkinsTest.java
> +            WebElement enterItemName = getDriver().findElement(By.xpath("//input[@name = \"name\"]"));
строки 16,19,22,25 - лучше используйте одинарные кавычки в локаторов

2023-05-13 14:42 UTC, VictoriaLema commented on src/test/java/school/redrover/NewItemJenkinsTest.java
> +        }
Ассерт?

2023-05-13 14:43 UTC, VictoriaLema requested changes
ложный аппрув

2023-05-13 15:17 UTC, ArinaJur commented
> Please add assert to your test. What are you verifying?
> 
> adding assert is not necessary. test is verifying creation of New Item, which indicated in AT name "CreateNewItem".

How would you sure that a new item was created? You can't see result on the server without assert

2023-05-14 03:05 UTC, VictoriaLema commented on src/test/java/school/redrover/NewItemJenkinsTest.java
> +public class NewItemJenkinsTest extends BaseTest {
все еще не дбавлена пустая строка между импортами и классом (7 строка должна быть пустой).
В последней лекции обсуждали. как лучше называть класс, посмотрите лекцию

2023-05-14 17:47 UTC, closed without merging

2023-05-14 17:48 UTC, davidmav19 commented
All Test passed as expected.