"testOpenWeather"
RedRoverSchool/JenkinsQA_06 pull request #180
Opened 2023-04-10 20:48 UTC by RykovaMariia

2023-04-10 20:51 UTC, olga-sumarokova approved these changes

2023-04-11 14:24 UTC, SafronovaOlga approved these changes

2023-04-12 17:11 UTC, eratheo requested changes
Строка 20 - передай туда chromeOptions

2023-04-12 18:03 UTC, eratheo approved these changes

2023-04-12 18:13 UTC, merged