added testCreateFolderTestFreestyleProgect US 01.03 | Freestyle project > Build now
RedRoverSchool/JenkinsQA_06 pull request #1826
Opened 2023-05-15 02:54 UTC by Dasha1991

2023-05-16 13:26 UTC, ArinaJur requested changes

2023-05-16 13:26 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        )));
You should click right after waiting:

getWait2().until(ExpectedConditions.elementToBeClickable(By.xpath("//a/span[contains(text(),'Build Now')]/parent::a" ))).click()

Rows 335 and 336 are unnecessary since your element is found and returned on row 334. Please re-watch last Sergey's lesson, where he explains this mistake

2023-05-16 13:26 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        WebElement projectStatusTable = getDriver().findElement(By.xpath("//table[@id = 'projectStatus']"));
Please add wait for this element as well

2023-05-16 15:18 UTC, Dasha1991 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        )));
у меня не сработал тест ,когда я в 333 строке написала click,поэтому вынесла отдельно webelement buildNowLink

2023-05-16 16:51 UTC, Dasha1991 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        getDriver().findElement(By.xpath("//button[@name ='Submit']")).click();
Я исправила тест.

2023-05-16 18:31 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        )));
Хорошо, пусть так будет, но получается двойной поиск одного и того же элемемнта. Если тест будет падать в этом месте, поставьте getWait5() или даже getWait10(), тк здесь создается конфигурация (отправляются API запросы) в добавок к переходу на новую страницу, потому нужно следить за этим местом и увеличивать время ожидания, если 2 сек не хватит

2023-05-16 18:33 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        WebElement projectStatusTable = getDriver().findElement(By.xpath("//table[@id = 'projectStatus']"));
@Dasha1991 Вы, наверное, исправили локально, но не закоммитили? Тк я изменений в тесте не вижу.

2023-05-16 19:33 UTC, Dasha1991 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        WebElement projectStatusTable = getDriver().findElement(By.xpath("//table[@id = 'projectStatus']"));
Cейчас вроде как все правильно закомитилось

2023-05-16 22:53 UTC, Dasha1991 commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        WebElement projectStatusTable = getDriver().findElement(By.xpath("//table[@id = 'projectStatus']"));
А вы можете снять с меня changes requested?Я понимаю,что пока оно весит ,я апрувел не получу

2023-05-17 12:32 UTC, ArinaJur requested changes

2023-05-17 12:32 UTC, ArinaJur commented on src/test/java/school/redrover/FreestyleProjectTest.java
> +        WebElement projectStatusTable = getDriver().findElement(By.xpath("//table[@id = 'projectStatus']"));
@Dasha1991 Я не могу с вас снять change requested, тк этот тест все равно придется игнорить позже, он не стабильный.
За 2 дня тест не был исправлен.
Ваш последний коммит - пустая строка.
предпоследний - исправлена одна строка, и не та, на которую был запрос
Напишите мне в слак - Irina(ArinaJur), напишите, когда вы можете выйти в зум. чтобы исправить PR

2023-05-17 21:42 UTC, ArinaJur approved these changes
LGTM

2023-05-18 03:06 UTC, Iriskus approved these changes

2023-05-18 03:10 UTC, merged