AT 04.15 | Folder > Move Multibranch Pipeline to Folder with dropdown menu
RedRoverSchool/JenkinsQA_06 pull request #1854
Opened 2023-05-15 18:25 UTC by lyudmila171

https://trello.com/c/djdqeJGv

2023-05-15 19:06 UTC, lyudmila171 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AT 04.15 | Folder > Move Multibranch Pipeline to Folder with dropdown menu](https://trello.com/c/djdqeJGv/1022-at-0415-folder-move-multibranch-pipeline-to-folder-with-dropdown-menu)

2023-05-15 20:52 UTC, ArinaJur requested changes

2023-05-15 20:52 UTC, ArinaJur commented on src/test/java/school/redrover/MultibranchPipeline3Test.java
> +        WebElement actualMultibranchPipeline = getDriver().findElement(By.xpath("//h1"));
Please add wait here. It is a new page,  without wait it could be unstable

2023-05-15 20:52 UTC, ArinaJur commented on src/test/java/school/redrover/MultibranchPipeline3Test.java
> +        WebElement actualMultibranchPipeline2 = getDriver().findElement(By.linkText("MultibranchPipeline1"));
This part is also potentially unstable without wait

2023-05-15 21:30 UTC, lyudmila171 commented on src/test/java/school/redrover/MultibranchPipeline3Test.java
> +        WebElement actualMultibranchPipeline = getDriver().findElement(By.xpath("//h1"));
@ArinaJur  please review changes

2023-05-15 21:30 UTC, lyudmila171 commented on src/test/java/school/redrover/MultibranchPipeline3Test.java
> +        WebElement actualMultibranchPipeline2 = getDriver().findElement(By.linkText("MultibranchPipeline1"));
@ArinaJur please review changes

2023-05-16 16:11 UTC, lyudmila171 commented on src/test/java/school/redrover/MultibranchPipeline3Test.java
> +        WebElement actualMultibranchPipeline = getDriver().findElement(By.xpath("//h1"));
@ArinaJur added one more 'wait' (row 54) when redirecting to the Project's 'Move' page, so all elements have enough time to display. Please review

2023-05-16 18:27 UTC, ArinaJur approved these changes

2023-05-16 18:43 UTC, elenavanesova approved these changes

2023-05-16 18:49 UTC, NataliaRamanenka approved these changes

2023-05-16 20:04 UTC, merged