Create configuration FreestyleProject Page
RedRoverSchool/JenkinsQA_06 pull request #2059
Opened 2023-05-20 20:23 UTC by ArtyomDulya

https://trello.com/c/pKMoeV4K/1343-rf-0000-pom-create-configuration-freestyleproject-page

2023-05-20 21:22 UTC, UlyanaVer approved these changes

2023-05-20 22:44 UTC, ke-de-ve requested changes

2023-05-20 22:44 UTC, ke-de-ve commented on src/test/java/school/redrover/NewProject3Test.java
> +                .selectDashboard();
стоит использовать переменную nameProject в строке
.enterItemName("Engineer2")

2023-05-20 22:44 UTC, ke-de-ve commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
уже есть 2 класса для этой страницы ConfigurePage и PipelineConfigPage в проэкте для одной страницы должен быть только один класс

2023-05-20 22:53 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
несогласен

2023-05-20 22:56 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
да есть страница PipelineConfigPage в которой конфигурируют PIpelineproject, а в моей странице конфигурируют FreestyleProject, я следующими PR я создам конфиги для каждого типа проекта, а вот страница ConfigurePage действительно ненужна

2023-05-20 22:58 UTC, ArtyomDulya commented on src/test/java/school/redrover/NewProject3Test.java
> +                .selectDashboard();
здесь согласен, в следующем pr это дело подправлю

2023-05-20 22:59 UTC, ArtyomDulya commented on src/test/java/school/redrover/NewProject3Test.java
> +                .selectDashboard();
Спасибо что заметили, следующим pr исправлю

2023-05-20 23:01 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
да есть страница PipelineConfigPage в которой конфигурируют PIpelineproject, а в моей странице конфигурируют FreestyleProject, а вот страница ConfigurePage действительно ненужна.

2023-05-20 23:05 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
есть страница PipelineConfigPage в которой конфигурируют PIpelineproject, а в моей странице конфигурируют FreestyleProject, у меня сложилась такая схема, в процессе тестирования Jenkins

2023-05-20 23:47 UTC, ke-de-ve commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
что мешает использовать ConfigurePage класс?   на этих страницах разные элементы?
Потом в проекте названия классов должны следовать одной схемею У нас уже есть класс 
PipelinePage и PipelineConfigPage  

может стоит продолжить эту практику?  
XyzPage и ZyxConfigPage 
FreestylePage и FreestyleConfigPage

2023-05-21 00:10 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
да, на этих страницах разные элементы

2023-05-21 00:22 UTC, ArtyomDulya commented on src/test/java/school/redrover/model/ConfigureFreestyleProjectPage.java
> +public class ConfigureFreestyleProjectPage extends BasePage {
Большая часть элементов аналогична, но у каждого типа проекта добавляются свои специфические настройки, каких нет в других

2023-05-21 00:22 UTC, ke-de-ve approved these changes

2023-05-21 00:50 UTC, merged