RF 00.00 job page and project page changed to basejobpage and baseprojectpage
RedRoverSchool/JenkinsQA_06 pull request #2412
Opened 2023-06-03 00:06 UTC by goluublue

https://trello.com/c/Hd3VrJJv

2023-06-03 06:47 UTC, ksutitova approved these changes

2023-06-03 08:11 UTC, SafronovaOlga approved these changes

2023-06-03 13:37 UTC, ke-de-ve requested changes

2023-06-03 13:37 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +
убери лишние пустые строки

2023-06-03 13:37 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +
убери лишнюю пустыю строку

2023-06-03 13:37 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +
Make sure empty line as a first line in method either in the every method or in none of them

2023-06-03 13:37 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseProjectPage.java
> +    public ConsoleOutputPage openConsoleOutputForBuild(int buildNumber){
missing space before {

2023-06-03 13:39 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseProjectPage.java
> +    public ConsoleOutputPage openConsoleOutputForBuild(int buildNumber){
Надо еще переделать методы возвращающие WebElement. Я вижу ты такую задачу уже прикркпил в Trello

2023-06-03 17:10 UTC, SergeiDemyanenko requested changes
А в чем отличие Job от Project, я думал, что это одно и тоже. Может названия дать разные или я чего-то не понял?

2023-06-03 17:10 UTC, SergeiDemyanenko commented on src/test/java/school/redrover/MultiConfigurationProjectTest.java
> +        WebElement newName = new MultiConfigurationProjectPage(getDriver())
Уже говорили несколько раз о том, что нельзя возвращать WebElement

2023-06-03 17:10 UTC, SergeiDemyanenko commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    protected void setupClickConfigure() {
Наверное стоит назвать clickSetupConfigure?

2023-06-03 17:10 UTC, SergeiDemyanenko commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    public WebElement getName() {
Прокомментировал выше

2023-06-03 17:34 UTC, goluublue commented
> понял

Есть две основных груп страниц Jobs у которых есть разные элэменты и возможности на их странице - Project, которые можна enable/disable; и Folder, которое содержит наружные элэмэнты. Есть еще OrganizationFolder и MultibranchPipeline, у которых есть некоторые элэмэнтов обоих Project и Folder; я не знаю как с ними разобратся. Пока просто собираю общие методы которые я знаю что есть во всех Jobs в BaseJobPage, и те которые есть в FreestyleProject, MulticonfigProject, и Pipeline в BaseProjectPage.

2023-06-03 18:08 UTC, goluublue commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    protected void setupClickConfigure() {
Этот метод будет вызыватся в реализации clickConfigure; во всех реализаций абстракта clickConfigure на каждой из шести вариантов Job страниц, будет вызыватся одинаковая логика прописана в этом setupClickConfigure, и потом создасться и возвротится нужная ConfigPage. Обяснение почему именно так сделано, пропишу ниже. Раз этот метод делает весь setup (подготовку) для clickConfigure, так его и назвал.

2023-06-03 18:08 UTC, goluublue commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    public WebElement getName() {
Не получилось сделать в форме дженерика, потому что ConfigPage уже берет 'JobPage на которую нужно вернутся' в ее конструкторе. Если дать конструктору JobPage 'тот ConfigPage, куда JobPage пошлет' как параметр, получится же как курица и яйцо. Это найменщее идиотический ответ на эту проблему, который я сам смог найти.

2023-06-03 18:13 UTC, goluublue commented on src/test/java/school/redrover/MultiConfigurationProjectTest.java
> +        WebElement newName = new MultiConfigurationProjectPage(getDriver())
My mistake

2023-06-03 19:36 UTC, ke-de-ve approved these changes

2023-06-04 19:57 UTC, RykovaMariia commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    public MovePage<Self> clickMoveOnSideMenu() {
этот метод не может быть общим для всех, т.к. move появляется только тогда, когда появляется папка, куда можно move

2023-06-04 20:43 UTC, goluublue commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    public MovePage<Self> clickMoveOnSideMenu() {
Возможно это и так, и не совсем идеально, но такие методы уже есть на большинстве существуюших JobPage; я пока просто консолидирую. Исправлять этот подход - отдельный PR.

2023-06-04 20:49 UTC, ke-de-ve commented on src/test/java/school/redrover/model/base/BaseJobPage.java
> +    public MovePage<Self> clickMoveOnSideMenu() {
Если это и делать, то в отдельном PR. 
@RykovaMariia создайте пожалуйста карточку в Трелло на исправление.

2023-06-04 20:49 UTC, merged