RF | MainHeaderComponent methods
RedRoverSchool/JenkinsQA_06 pull request #2528
Opened 2023-06-09 18:21 UTC by DaryaSLN

https://trello.com/c/74wzzOxi

2023-06-09 20:23 UTC, nikabenz approved these changes

2023-06-09 20:27 UTC, alex-evt approved these changes

2023-06-09 20:28 UTC, merged

2023-06-09 20:35 UTC, Maria7725 requested changes

2023-06-09 20:35 UTC, Maria7725 commented on src/test/java/school/redrover/model/component/MainHeaderComponent.java
> +    private void clickDashboardDropdownMenu(By subMenu) {
Darya, у меня возник вопос: что это за subMenu которое передается в метод, как параметер? Похоже, что это какой-то локатор. Почему он так называется и почему он передается, как параметер?

И не ясно, почему "clickDashboardDropdownMenu" метод сделан void. Чтобы мы не кликали, мы всегда попадаем на ту или иную страницу, которую метод и должен возвращать.

2023-06-10 08:28 UTC, DaryaSLN commented on src/test/java/school/redrover/model/component/MainHeaderComponent.java
> +    private void clickDashboardDropdownMenu(By subMenu) {
Maria, subMenu - локатор элемента из списка подменю, которое появляется при наведении мыши на Manage Jenkins в списке выпадающего меню (DashboardDropdownMenu). 

При вызове методов в тестах мы не можем передавать в них локаторы, в тестах вообще не должно быть локаторов, поэтому этот метод сделан приватным и ничего не возвращает, но его можно использовать при написании методов, позволяющих переходить с одной страницы на другую через подменю.

2023-06-11 20:47 UTC, Maria7725 commented on src/test/java/school/redrover/model/component/MainHeaderComponent.java
> +    private void clickDashboardDropdownMenu(By subMenu) {
Darya, спасибо за ответы, стало яснее. Похоже, мое непонимание вызвано названиями методов. 
1) Мне кажется, что метод "clickDashboardDropdownMenu()" можно было бы назвать "openDashboardDropdownMenu". "ClickDashboard" немного сбивает с толку, т.к. по Dashboard действительно можно клиунуть, но метод делает другое. Хотя, конечно, слова DropdownMenu в названии подсказывают о чем 
 идет речь)).
 2) Мне кажется, было бы понятнее если бы в названии метода "clickDashboardDropdownMenu(By subMenu)" были бы слова "clickOnSubmenu", но, возможно, это тоже дело вкуса или привычки.