added BaseTest, added SecondTest, changed and refactored FirstTest
RedRoverSchool/JenkinsQA_06 pull request #469
Opened 2023-04-14 05:39 UTC by matsstang

2023-04-14 23:55 UTC, closed without merging

2023-04-14 23:56 UTC, Maria7725 requested changes

2023-04-14 23:56 UTC, Maria7725 commented on src/test/java/school/redrover/PetroMatsiuraBaseTest.java
Петро, методы BeforeMethod, AfterMethod and getDriver вынесены в класс BaseTest, и больше в тестах не нужны (наш класс наследует класс BaseTest)

2023-04-14 23:56 UTC, Maria7725 commented on src/test/java/school/redrover/PetroMatsiuraFirstTest.java
BeforeMethod здесь не нужен, см. первый комментарий. 
Проверьте пожалуйста что слип необходим и не может быть меньше 3 секунд. Сергей на лекции просил добавлять их только если очень нужно и делать короткими

2023-04-14 23:56 UTC, Maria7725 commented on src/test/java/school/redrover/PetroMatsiuraFirstTest.java
BeforeMethod не нужен, см. первый комментарий.

У вас перед Assert иногда есть пустая строка, а иногда нет. Мне кажется, что перед assert всегда нужна пустая строка.

2023-04-15 00:13 UTC, matsstang commented on src/test/java/school/redrover/PetroMatsiuraFirstTest.java
Thanks
I'll fix it asap