Add Test
RedRoverSchool/JenkinsQA_06 pull request #514
Opened 2023-04-14 21:04 UTC by davidmav19

2023-04-14 22:12 UTC, elviraKh1 requested changes
You deleted AndriiKudlaTest.java .

2023-04-14 22:14 UTC, bnovikov09 approved these changes
ok

2023-04-14 22:14 UTC, IraKalinka reviewed
ты не там создал класс. создавать надо в папке school.redrover

2023-04-14 22:15 UTC, IraKalinka commented
> You deleted AndriiKudlaTest.java .

это не он удалил, а я перенесла.

2023-04-14 22:16 UTC, elviraKh1 submitted a review, later dismissed

2023-04-14 22:16 UTC, elviraKh1 commented
Ш 

> ok



> > You deleted AndriiKudlaTest.java .
> 
> это не он удалил, а я перенесла.
 ok

2023-04-14 22:19 UTC, elviraKh1 commented
> ты не там создал класс. создавать надо в папке school.redrover

да, надо добавить package school.redrover;

2023-04-14 23:14 UTC, elviraKh1 approved these changes

2023-04-14 23:28 UTC, elviraKh1 commented on src/test/java/school/redrover/DavidMTest.java
> +    public void TestSecond() throws InterruptedException {
next time use lower case for test names

2023-04-15 01:26 UTC, merged

2023-04-15 16:52 UTC, davidmav19 commented
First successful test